name: example
description: "Swift UI Example App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-131.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  swift_ui:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/dash_hello/dash_hello.png